baseURL: "https://agrest.io/"
languageCode: "en-us"
title: "Agrest: Java REST API Framework | Official Website"

params:
  description: Explore Agrest, a Java REST API framework for efficient data services. Supports CRUD, JAX-RS, Cayenne ORM, and provides fine-grained security over HTTP/JSON.

disableKinds:
  - RSS
  - taxonomy
  - term

enableRobotsTXT: true

permalinks:
  page: ":filename/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Getting Started"
      url: "/docs/5.x/getting-started/"
      weight: 2
    - name: "Documentation"
      url: "/docs/"
      weight: 3
    - name: "Forum"
      url: "https://groups.google.com/forum/?#!forum/agrest-user"
      weight: 4