baseURL: "https://agrest.io/"
languageCode: "en-us"
title: "Agrest - Model-Driven REST Data Services"

disableKinds: ['RSS', 'taxonomy', 'term']

permalinks:
  page: ":filename/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Getting Started"
      url: "/docs/5.x/getting-started/"
      weight: 2
    - name: "Documentation"
      url: "/docs/"
      weight: 3
    - name: "Forum"
      url: "https://groups.google.com/forum/?#!forum/agrest-user"
      weight: 4